export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_TRANSACTIONS_DONE = "GET_TRANSACTIONS_DONE";
export const POST_TRANSACTION = "POST_TRANSACTION";
export const POST_TRANSACTION_DONE = "POST_TRANSACTION_DONE";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const DELETE_TRANSACTION_DONE = "DELETE_TRANSACTION_DONE";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_TOTAL_INCOME = "SET_TOTAL_INCOME";
export const SET_TOTAL_EXPENSE = "SET_TOTAL_EXPENSE";
export const SET_TOTAL = "SET_TOTAL";

export const SET_TRANSACTION_ACTIVE = "SET_TRANSACTION_ACTIVE";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const REMOVE_ALL = "REMOVE_ALL";
