export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_TRANSACTION_ACTIVE = "SET_TRANSACTION_ACTIVE";
export const SET_TOTAL_INCOME = "SET_TOTAL_INCOME";
export const SET_TOTAL_EXPENSE = "SET_TOTAL_EXPENSE";
export const SET_TOTAL = "SET_TOTAL";
export const REMOVE_ALL = "REMOVE_ALL";
