export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const SIGN_IN_WITH_GOOGLE = "SIGN_IN_WITH_GOOGLE";
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD = "SIGN_IN_WITH_EMAIL_AND_PASSWORD";
export const SIGN_OUT = "SIGN_OUT";
export const CREATE_USER_WITH_EMAIL_AND_PASSWORD = "CREATE_USER_WITH_EMAIL_AND_PASSWORD";
